---
title: ''
author: 'William Komu'
date: '`r Sys.Date()`'
document:
  pdf_document:
    self_contained: false
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

## Load libraries

```{r loads_libs}
library(tidyverse)
library(ggthemes)
library(janitor)
library(gifski)
library(gganimate)
library(ggplot2)
library(lubridate)

#options
options(browser = "firefox")
```

## Quiet tidyverse

Since the `tidyverse` pkg tends to be overly chatty, this is a queit way to call it!

```{r, eval = requireNamespace("tidyverse", quietly = TRUE)}
library(tidyverse)
```

## Load data

```{r}
owid_le <- read_csv("/home/iamlnx/Documents/GitHub/nasoma_R/global_life_exp/data/OWID/life-expectancy-OWID-data.csv") %>%
  rename(country = Entity, country_code = Code, year = Year, life_expectancy = "Life expectancy at birth (historical)") %>%
  mutate(year = as.numeric(as.character(year))) %>%
  select(year, country, life_expectancy)
```

## Kenya

```{r}
kenya_le <- owid_le %>%
  filter(country %in% c("Kenya")) %>%
  select(year, country, life_expectancy)

kenya_le

ln_p_ke_anim <- kenya_le %>%
  ggplot(aes(year, life_expectancy, color = country)) +
  geom_point(aes(size = life_expectancy), show.legend = FALSE) +
  geom_line(aes(color = country)) +
  scale_x_continuous(limits = c(1920, 2030), expand = c(0, 0)) +
  theme_economist() +
  theme(
    axis.text.x.bottom = element_text(margin = margin(b = 10)),
    axis.text.y.left = element_text(margin = margin(l = 10)),
    legend.title = element_blank()
  ) +
  transition_reveal(along = year)

animate(ln_p_ke_anim)

# theme_void() +nt_te
# theme(plot.background = element_rect(fill ="white"))

ggsave("figures/kenya_le_owid.png")
```

##

The code chuck below helps us to preview the extreme ends of the data for the various countries of interest and the global_le as a whole!

```{r}

```

## kenya_le:
- min_year  = 1927
- max_year  = 2021
- min_le    = 23.9
- max_le    = 62.9
## global_le:
- min_year  = 1543
- max_year  = 2021
- min_le    = 12
- max_le    = 86.5
